version: '3.8'  # Versión de la especificación de Docker Compose

services:
  postgres:
    image: postgres:14  # Imagen de Docker para PostgreSQL
    container_name: postgres  # Nombre del contenedor
    environment:  # Variables de entorno para la configuración de PostgreSQL
      POSTGRES_USER: myuser  # Usuario de PostgreSQL
      POSTGRES_PASSWORD: mypassword  # Contraseña del usuario de PostgreSQL
      POSTGRES_DB: mydatabase  # Nombre de la base de datos
    ports:
      - "5432:5432"  # Mapeo del puerto 5432 del host al puerto 5432 del contenedor
    volumes:
      - db-data:/var/lib/postgresql/data  # Volumen para persistir los datos de PostgreSQL
    networks:
      - mynetwork  # Red en la que el servicio estará

  pgadmin:  
    image: dpage/pgadmin4:latest  # Imagen de Docker para pgAdmin
    restart: always  # Política de reinicio para el contenedor
    container_name: pgadmin  # Nombre del contenedor
    depends_on:
      - postgres  # Dependencia del servicio postgres
    environment:  # Variables de entorno para la configuración de pgAdmin
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Email por defecto para pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin  # Contraseña por defecto para pgAdmin
      PGADMIN_LISTEN_PORT: 80  # Puerto en el que pgAdmin escuchará dentro del contenedor
    ports:
      - "8080:80"  # Mapeo del puerto 80 del contenedor al puerto 8080 del host
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Volumen para persistir los datos de pgAdmin
    networks:
      - mynetwork  # Red en la que el servicio estará

volumes:
  db-data:  # Volumen para los datos de PostgreSQL
  pgadmin-data:  # Volumen para los datos de pgAdmin

networks:
  mynetwork:  # Definición de la red mynetwork
